### ISSUE TITLE
Peer to Peer Review: Code check-up

### ISSUE THREAD

**Issue by Peter-Kibet** [devendra-alt/ES6-capstone#39]
![AmazingHowieMandelGIF](https://github.com/devendra-alt/ES6-capstone/assets/87215764/313e30f0-6dfb-462b-91ab-e0c8d4cc69d4)
🌟Great workflow
🏆Good job on following the best practices

**Comment by devendra-alt** [comment]
![](https://media.giphy.com/media/26FPOogenQv5eOZHO/giphy.gif)
